### ISSUE TITLE
Update NGINX

### ISSUE THREAD

**Issue by khdc-me** [khdc-me/ws-kevinharper-v2#39]
Update NGINX docker image to 1.19.0-alpine.

NOTE: Current image used is 1.17.10-alpine.

**Comment by TechTucson** [comment]
I can take care of this if needed, please let me know.

**Comment by khdc-me** [comment]
Please. It's ready for you to do it.

**Comment by khdc-me** [comment]
Please push to the following branch:

update-nginx
